CREATE DATABASE [dbAlavancas]
ON  PRIMARY (
NAME = N'dbAlavancas',
FILENAME = N'C:\ARQUIVO_DADOS\dbAlavancas.MDF',
SIZE = 100MB,
MAXSIZE = 300MB,
FILEGROWTH = 50MB )
LOG ON (
NAME = N'dbAlavancasLOG',
FILENAME = N'C:\LOG_TRANSACOES\dbAlavancasLOGLOG.LDF',
SIZE = 100MB,
MAXSIZE = 300MB,
FILEGROWTH = 50MB );